services:
  spharm-processor:
    image: spharm_analysis
    container_name: spharm-processor
    ports:
      - "8787:8787"
    environment:
      - DISABLE_AUTH=${DISABLE_AUTH:-true}
      - PASSWORD=${RSTUDIO_PASSWORD:-spharm}
      - RENV_PATHS_LIBRARY=/opt/renv/library
      - RENV_PATHS_CACHE=/opt/renv/cache
    volumes:
      # mount the project (the directory containing this compose file) at /project
      - .:/project
    working_dir: /project
    stop_grace_period: 1s
    restart: "no"